### PR TITLE
Use equality contraints while solving

### LINKED ISSUE #13: Doesn't work in local (where-bound) function?
The following code fails to typecheck:

```
{-# LANGUAGE GADTs, ScopedTypeVariables, DataKinds, KindSignatures #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE Rank2Types #-}

{-# OPTIONS_GHC -fplugin GHC.TypeLits.KnownNat.Solver #-}

import Data.Singletons.Prelude.Num
import Data.Singletons
import GHC.TypeLits

data Foo :: Nat -> * where
  FZ  :: Foo 0
  FS :: Foo n -> Foo (n + 1)

sPred :: (KnownNat n) => Sing (n+1) -> Sing n
sPred _ = sing

foo :: forall a n. (KnownNat n) => a -> (forall m. KnownNat m => Sing m -> a) -> Foo n -> a
foo x0 f = go (sing :: Sing n)
  where
    go :: forall k. (KnownNat k) => Sing k -> Foo k -> a
    go s FZ = x0
    go s (FS _) = f (sPred s)
```

The error message is as follows (on GHC 8.0.2):

```
KnownNatSolverBug.hs:25:19: error:
    * Could not deduce (KnownNat n1) arising from a use of `f'
      from the context: KnownNat n
        bound by the type signature for:
                   foo :: KnownNat n =>
                          a -> (forall (m :: Nat). KnownNat m => Sing m -> a) ->
        at KnownNatSolverBug.hs:20:1-91
      or from: KnownNat k
        bound by the type signature for:
                   go :: KnownNat k => Sing k -> Foo k -> a
        at KnownNatSolverBug.hs:23:5-56
      or from: k ~ (n1 + 1)
        bound by a pattern with constructor:
                   FS :: forall (n :: Nat). Foo n -> Foo (n + 1),
                 in an equation for `go'
        at KnownNatSolverBug.hs:25:11-14
      Possible fix:
        add (KnownNat n1) to the context of the data constructor `FS'
    * In the expression: f (sPred s)
      In an equation for `go': go s (FS _) = f (sPred s)
      In an equation for `foo':
          foo x0 f
            = go (sing :: Sing n)
            where
                go :: forall k. (KnownNat k) => Sing k -> Foo k -> a
                go s FZ = x0
                go s (FS _) = f (sPred s)
```

To highlight, the relevant parts of the context are:

```
    * Could not deduce (KnownNat n1) arising from a use of `f'
      from: KnownNat k
      or from: k ~ (n1 + 1)
```

But isn't this exactly the situation that the plugin was designed to handle?

### LINKED ISSUE #42: Intermediate type variable stops derivation of `KnownNat` constraint
Occurs after partially fixing [#65 ](https://github.com/clash-lang/ghc-typelits-natnormalise/issues/65) reported in the natnormalise plugin by @lmbollen.

This test:

```
test29 :: forall a b . (b ~ (2^a)) => SNat a -> SNat (Log b)
test29 SNat = SNat @(Log b)
```

Fails with:

```
Could not deduce (KnownNat b) arising from a use of ‘SNat’
    from the context: b ~ (2 ^ a)
      bound by the type signature for:
                 test29 :: forall (a :: Nat) (b :: Nat).
                           (b ~ (2 ^ a)) =>
                           SNat a -> SNat (Log b)
      at tests/Main.hs:187:1-60
```

Even though it should be able to derive the `KnownNat` constraint from the `KnownNat a` given constraint.

### PR DESCRIPTION
**Pull request by christiaanb**
Fixes #13
Fixes #42

### CODE REVIEW

**Comment by christiaanb** [comment]
@sheaf This PR no longer drops the dependencies generated by `normalizeNat` and also keeps around the dependencies generated by `splitTyConApp_upTo`; I think that should satisfy proper dependency tracking for the `mkPluginUnivCo` stuff that this plugin does.

File: src/GHC/TypeLits/KnownNat/Solver.hs [hunk 1]
```diff
@@ -339,16 +341,19 @@ constraintToEvTerm defs givensTyConSubst givens (ct,cls,op,orig) = do
...
     -- type-level operation
-    go :: (Type, Maybe Coercion) -> TcPluginM Solve (Maybe (EvTerm,[Ct]))
-    go (coreView -> Just tyN, coM) = go (tyN, coM)
-    go (go_other -> Just ev, _) = return (Just (ev,[]))
-    go (ty@(TyConApp tc args0), sM)
+    go :: [Coercion] -> (Type, Maybe Coercion) -> TcPluginM Solve (Maybe (EvTerm,[Ct]))
+    go deps (coreView -> Just tyN, coM) = go deps (tyN, coM)
+    go deps0 (ty, coM)
+      | Just ((tc,args,deps1@(_:_)) :| []) <- splitTyConApp_upTo givensTyConSubst ty
+      = go (deps0 <> deps1) (TyConApp tc args, coM)
```
Comment (sheaf) [inline src/GHC/TypeLits/KnownNat/Solver.hs]: I think you should handle longer lists as well. In `ghc-typelits-natnormalise` I use `asum`, so something like:

```hs
    go deps0 (ty, coM)
      | Just tcapps <- splitTyConApp_upTo givensTyConSubst ty
      = do results <- traverse ( \ (tc, args, deps1) -> go (deps0 <> deps1) (TyConApp tc args, coM) ) tcapps
           return $ asum results
```

**Review by sheaf — APPROVED** [review]

File: src/GHC/TypeLits/KnownNat/Solver.hs (hunk 1 above)
Comment (christiaanb) [reply src/GHC/TypeLits/KnownNat/Solver.hs]: Alright, done!
